### PR TITLE
ENT-3772 mobile css filter col fix

### PR DESCRIPTION
**Pull request by edx-abolger**
Small CSS fix:  On mobile view, filters on the admin portal learner table should be in a single column.

### CODE REVIEW

**Comment by edx-abolger** [comment]
Before and after: 
Screen Shot 2020-12-15 at 6 37 43 PM
Screen Shot 2020-12-15 at 6 38 09 PM

**Review by raq929 — APPROVED** [review]
LGTM! 
Before you merge, I just want to confirm that this changes the columns on mobile only, correct?

**Comment by edx-abolger** [comment]
> LGTM!
> Before you merge, I just want to confirm that this changes the columns on mobile only, correct?

The changes based on the Bootstrap grid system only appear on xs and sm size screens. I used md as the breakpoint because sm and xs are when the rest of the layout switches to single column.  See screenshot for unchanged 'md' screen size layout. 

Screen Shot 2020-12-16 at 12 27 59 PM

**Comment by raq929** [comment]
Perfect, you're good to merge. :)

**Pull request merged**
